### ISSUE TITLE
ComicrackCE will not load

### ISSUE THREAD

**Issue by Azrael102415** [maforget/ComicRackCE#117]
After installing the most recent nightly installer the program will not load. It gets suck on the splash screen at "loading Database" and runs in the background but never loads to the User Interface.

![image](https://github.com/user-attachments/assets/9eb8fc24-577a-46d5-bd56-29a0e04d9cb1)

![image](https://github.com/user-attachments/assets/eebdfb22-7550-4902-a11d-ca3dc5ca205e)

Task manager does show program is running in the background.

I have restarted the computer i have uninstalled and reinstalled as well with no success.

**Comment by maforget** [comment]
The latest update was simply some libraries that were updated that have nothing to do with the database. Just updating the PDF engine, JSON & SharpCompress which is an alternative to 7-Zip for opening the files.

This looks like a corrupted database. Maybe when you updated the previous version was open and it corrupted the database. Check to replace the .bak version of the database or a backup you had. Location is `%appdata%\cYo\ComicRack Community Edition`.

This [reddit thread](https://www.reddit.com/r/comicrackusers/comments/ncy316/comicrack_not_opening_win10_v2004/) talk about a similar issue that was present before CE even existed, so pretty sure it isn't related to the update, just a coincidence. And the TLDR was that the file was corrupted because of a failing HD. 

You could provide your `ComicDb.xml` file for testing.

**Comment by Azrael102415** [comment]
You are correct. After about 30 minutes it finally did load and say the DB was corrupted and a new one was loaded. I am sorry that I didn't make it back on here to update the ticket I have been busy rebuilding and readding everything because I did not have a backup file.
