### ISSUE TITLE
Plugin "Backup for Comicrack" don't work with CE Edition

### ISSUE THREAD

**Issue by sevymic** [maforget/ComicRackCE#26]
Hi
The plugin "Backup for Comicrack" don't works with CE edition because it's store the "%APPDATA%/cYo/ComicRack" folder and not the "%APPDATA%/cYo/ComicRack Community Edition"
Here is the link to the plugin : https://code.google.com/archive/p/cr-backup-manager/

Very useful plugin. It zip the ComicRack folder with ComicDB.xml each time CR starts. Can do a full backup too.

**Comment by maforget** [comment]
Yes I know, I mentioned it on Reddit already. But this isn't a ComciRackCE bug, this shouldn't be an Issue. There is nothing we can do, only the plugin author (or someone who wants to update it, should update it.

The plugin also doesn't work with portable installations because of that. The plugin author should have detected the location that the plugin starts in and work from there.  I've updated my local installation by just changing the path.

I will be closing it, but feel free to post it in the discussion section with a fixed version for other to get.
