### ISSUE TITLE
Drag & drop in folder treeview form

### ISSUE THREAD

**Issue by killo3967** [maforget/ComicRackCE#58]
Do you think it could be a good idea to drag and drop folders in the treeview of the folder view, instead of go out to explorer, move folders and then reload the library ?

**Comment by maforget** [comment]
That might be fine with your workflow, but I see it as a very bad idea.

My guess is that you have folders to be scanned when opening and remove the file that are missing at the same time. You really should be using Library Organizer instead of moving folder around and reloading. 

But consider my workflow where no folder is automatically loaded, I go to the Folder tab to only 1 folder where all unorganized files are. Add the manually to the library, scrap and move them with Library Organizer. Imagine in that case that I accidentally move a folder, then all my files will have a big red X on them and not be found. 

So it's very prone to errors and honestly you shouldn't be doing that in the first place.

**Comment by killo3967** [comment]
I see that lately we don't agree much in our opinions. What you say about using Library Organizer may be very good in certain cases, but for me, who doesn't have anything from Marvel or DC, it would force me to create more than 100 rules since I touch on many topics. That's why it's done manually. It's not a very heavy job either. But if doing what I ask of you is too complex, then I continue doing it by hand, as I have been doing until now.

**Comment by maforget** [comment]
Not really certain where else we might have differing opinions, I really don't really pay attentions to the names of those who comments. I believe your comments were about the plugin system #3, and I do agree with you that Python is usually preferred by non-developer. I just wanted to make clear that the existing plugin system isn't going anywhere, because all the comments were all suggesting that the current python system would be removed. I wanted to make it very clear that it's staying and if anyone want to code in python they still can.

It's not a question of being too complex, I am more concern with adding feature that might affect others that aren't aware of it and how it may affect them. I need to think big picture, with all kinds of users and not accept all requests without some thinking on the impact it will have.

Let's be frank most computer users I've encountered don't even go into the settings and when they do something they always blame the program or developer. Right now only a pretty small circle of die hard users are aware of this project. But as more people become aware and we have a solid release with a LOT of changes there could be a bigger influx of users. Most that don't even know what Github is let alone, read a wiki or go to the subreddit.

Maybe it's because of my own IRL frequentations, but I always tend to think of the worst possible case. You won't believe the people I know that always say that things move on their own or don't even understand a file system. Maybe they aren't the core audience for this program, but sometimes the same questions that keep popping up on reddit makes me wonder. So I can't help but imagine someone moving a folder in the program either aware or not, and might not realize they are affecting the file system.  Then wondering why all it's file are missing. It probably as a way bigger chance of occurring then your use case.

I also can't think of a program that has that kind of file browser built-in that let's you move affect explorer folders (beside thing where that is the first purpose like Total Commander) . Is that something that is widespread? I can't think of any right now.

It's also because I see an alternative to your use case. It's probably better to make the plugin work for you than anything else. Library Organizer use isn't just useful for things like Marvel or DC. I know that the Organizer Guide is focused on them, but doesn't mean it's the only way to use it. If you would need 100 rule, then maybe a different way of thinking is required. You could use Rules, Conditionals or just Custom fields (or Tags) to help organize your library. If you need any help, I am happy to help.

I ain't saying no, and I am open to PR. But that would require a setting to be enabled first to prevent unwanted changes. But I am still skeptical if this kind of function has a place. Maybe others can give their opinions.

**Comment by killo3967** [comment]
The first thing is to apologize if the initial comment bothered you, but it was more towards you that I was referring to. It is a popular expression that we use when two people do not usually have the same opinion, without further pretensions.
Regarding the plugin you mention, I use it, as I have understood it, for comic series that are in an "ongoing" state, and certainly some that I have are in that state. However the series I get are usually finished and it's not really worth creating a rule for a single movement. On the other hand, this plugin requires that the comics already have metadata and what I do is download them, clean them internally, name them correctly, move them to the destination folder and at the end use the plugins to obtain metadata. This is why I thought it would be good, instead of doing it with an explorer, to do it directly within Comicrack, but I understand that in these initial moments and with so many (and more important) changes in the structure of the program, my idea is not a priority. Nor do I pretend it is. At most, prop it up there in case one day there is time or desire. 
I just have to thank you for reviving this project, which I think is most interesting, and for the great work and time you are dedicating to it.

**Comment by maforget** [comment]
> However the series I get are usually finished and it's not really worth creating a rule for a single movement.

That is what I wanted to say. There are no need to have different rule for a single serie. I use maybe 4, 1 for French comics, another for Manga's, one for series like DC and the last one is a catch all for everything else. Since they are all stacked on top of each other I just run the tool and it's all determined automatically.

90% of all my imports use that single catch all rule. I first use PRIAT to import some data based on the name of the file. I use the data to determine which folder they can go to, with Data Manager settings up some of this data automatically. For example I can set a Series Group in LIbrary Organizer, if the field is empty it won't create a folder. If I want them inside a subfolder, all I need to do is select the files add a Series Group (or do it via Data Manager) and the files go into the right subfolder, without the need for multiple rules.

What is to stop you from adding the data before and let the data determine the location.

**Comment by killo3967** [comment]
Thanks. I'll study it.
