### ISSUE TITLE
Co-existance with OG ComicRack

### ISSUE THREAD

**Issue by DieselTech** [maforget/ComicRackCE#6]
Seems like both versions can't exist at the same time on a system. Even opening the OG .exe file directly from it's folder will launch the new CE version.

![image](https://github.com/maforget/ComicRackCE/assets/30128380/896da476-ae79-4ecc-a4e5-7e289a5c6a66)

**Comment by maforget** [comment]
Check again, they can be used on the same system. What you probably experienced is that the old one was still in the system tray. And since the new one has a new Configuration folder, the default behavior of being in the tray is enabled and the new program is hidden by default from windows. You probably didn't see it still running so when starting the OG, it opens the one that is already open (since both have the same name, it can't differentiate between).

I've been using both version for years. I version to test and debug stuff and the original version that I still use.

**Comment by DieselTech** [comment]
Hm. That might of been what it was doing. Was just weird that I was specifically launching the OG exe and the CE would load.
