### ISSUE TITLE
Tags textbox are still disabled when multiple books is selected.

### ISSUE THREAD

**Issue by TheRealC0unt** [maforget/ComicRackCE#76]
Thank you very much for fixing that old annoying issue, that the tags someone adds to a comic or series never were stored in the comicinfo.xml files.

Though, this is still only less than half the mileage to go. So far, storing the tags only works for files which have been already added to the library. It does not work for files which you access through the file browser tab. You can add them (though the field is grayed out, but the dialog still opens up), but they are not stored permanently, and especially they are not exportted to comicinfo.xml then.
It took a while for me to recognize this.

I'd really appreciate if tagging would work absolutely the same way as adding genres, because right now it is a nuisance in my workflow.
When I get new comics or mangas, I store them on the local SSD of the notebook first, to add info by comicvine scraper and manually. Only when there is already some good comicinfo.xml in each file, it will be stored at its final location on my NAS, where a Komga server instance then picks the stuff up.
If I always have to move the files first prior to adding the tags, this is slowing down the workflow significantly, especially when connected by WIFI, not by LAN. With bad timing, it can even happen that the Komga server has to swallow the new stuff twice, due to its feature to automatically grab new directories every x hours.

**Comment by maforget** [comment]
It does work and I did test it. And the Tags field does work when in the file browser. I use all the time. I added a tag, updated the file and open with 7-zip to read the xml, and the tags field was there. This commit is even where this was enabled. https://github.com/maforget/ComicRackCE/commit/631dbb4360520f7aa19f837c7dff2919e2262579

I don't know what you are doing, but I can guarantee that the problem isn't with the software. You either are using an old build, are getting mixed up with ComicRack & ComicRack Community Edition (Settings from one don't automatically port over to the other) or you have something preventing the files from updating. If you know that there is a problem post a detailed way to reproduce it.

See the Tags field is enabled. You can see it's from the file browser because the Series Complete is disabled, like in the code posted above. Before that change the Tags field would have been disabled also. If you don't see it you either on a old build or still using the Original ComicRack.
![Screenshot 2024-05-18 050409](https://github.com/maforget/ComicRackCE/assets/11904426/56f261ac-5845-4b49-8f43-fe16c4b03211)

And it appears in the xml, after an update file
![Screenshot 2024-05-18 050430](https://github.com/maforget/ComicRackCE/assets/11904426/668ccc10-a935-4504-a24a-954a9f4853a3)

Here is even a GIF that proves it works:
![ComicRack_2024-05-18_05-09-18](https://github.com/maforget/ComicRackCE/assets/11904426/b3cb9cdc-d255-4c0b-a3c0-319bf16168ed)


If it isn't then it means that option isn't turned on.
![Screenshot 2024-05-18 045010](https://github.com/maforget/ComicRackCE/assets/11904426/63c80a68-44e1-445d-960a-dc3876ca5357)

**Comment by maforget** [comment]
Ok I agree that the field is still disabled when choosing multiple files. But your initial bug report was that the Tags where not updated in the `ComicInfo.xml`. This is still false. Like you stated there are other way to update it. Like for example while using PRIAT, you can add a Tags. If you talk about using the little star to add a Tags that isn't the same, the field is still disabled. 

Even with the field disabled, if you add Tags via a plugin for example and update the file, the `ComicInfo.xml` is still updated. And they are store permanently.

I will fix the issue with the UI, but when doing bug reports there is a reason why in the template I provided I ask for the commit version, to be certain which version some one is using and if that is an old build. There is also a difference between the UI is greyed out when using multiple books, vs one and the update of `ComicInfo.xml` doesn't work like you stated.
