### ISSUE TITLE
Page Type options are greyed out

### ISSUE THREAD

**Issue by J4k17** [maforget/ComicRackCE#94]
Hello, first off thankyou to the people involved for keeping this app alive and contributing to it, I'm returning after a long time away from comics, and I'm glad to see a familiar app face.
(Repost from Reddit).

**Describe the bug**
I'm having a problem with CCE, in that the Page Type options are greyed out with "Story" being the only option.

**Exact Steps to Reproduce**
1. Go to 'Edit' Top Menu
2. Click on 'Page Type'
3. Options are greyed out with "Story" being the only option
4. Have added to Library, as per instructions found in google, did not resolve the issue.

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: [ebe5d65] 64 bit

I've done a fair bit of googling this and have come up blank. Is this the norm for everyone or am I missing somthing?

I've added to library and still no go.

tia J

**Comment by maforget** [comment]
You won't be able to change the Page Type, if a book isn't opened. The reason for the menu is to change the type of the displayed page, so if no pages shown, the menu is disabled.

The menu appears in the Library, because you can have the reader docked to the library having a book opened at the same time you are browsing.

**Comment by J4k17** [comment]
Hey maforget,
Thankyou for the explanation, I inderstand now.

J
